frequency: 30  # Hz
sensor_timeout: 0.1
two_d_mode: true

# Specify inputs (IMU, odometry, GPS)
odom0: /odom
odom0_config: [true, true, true, true, true, true,  # x, y, z, roll, pitch, yaw
               false, false, false, false, false, false]  # vx, vy, vz, vroll, vpitch, vyaw

imu0: /imu/data
imu0_config: [false, false, false, true, true, true,
              false, false, false, true, true, true]

world_frame: map
base_link_frame: base_link
odom_frame: odom
